### PR TITLE
Refactored the version check and fix a misspelling

### PR DESCRIPTION
**Pull request by radondev**
- An actual version system would be more effective, but kind of an overkill for this project

Personally, I'd prefer to improve the code style of SAC in this rewrite rather than sticking to the old one. Type declarations and PHPDoc can speed up the developing process and should be a standard in 2020. It's easier to read the code, understand its functionality and work with it in general.

### CODE REVIEW

**Comment by DarkWav** [comment]
Oof, I didn't see that PR before I coded that myself, but thanks for the Idea!
I'll give you some credit in the plugin.yml

**Comment by DarkWav** [comment]
I'll take a look at PHPDoc and Type declarations, but my time is limited so I'm not sure how fast I'll be able to implement it.

**Comment by radondev** [comment]
Sure, it's just a suggestion ^^

I'll try to help if can

**Comment by DarkWav** [comment]
I've added some declarations in 8178e52568e6f73e9d16121385b967fa783df1f1 similar to the way they exist in PocketMine-MP.
Enforcing them in the actual code would require a lot of otherwise unnecessary imports so I don't know if that's the ideal solution.

**Comment by radondev** [comment]
The imports aren't really unnecessary, as it ensures that the passed object is of the correct type.

On the other hand, it's nice to speed up development and understand the code better, as you can _see_ what is passed without backtracing the function call. I don't know what your development environment looks like, but most modern IDEs import the classes automatically.

**Comment by DarkWav** [comment]
Of course you would enforce declarations in C++, Java, ect, but I think I'll stick to PocketMine-MP's way of doing things as this is a plugin for PMMP.

Most of the time I don't really use any IDE but a plain text editor with some enhancements (I know that's stupid xD)

**Pull request closed without merging**
